CREATE TABLE users (
		id UUID PRIMARY KEY,
		name VARCHAR NOT NULL UNIQUE,
		api_key VARCHAR NOT NULL UNIQUE,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE recipe_extractions (
		id UUID PRIMARY KEY,
		user_id UUID REFERENCES users(id) ON DELETE CASCADE,
		data JSONB NULL,
		metadata JSONB NOT NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);