name: CI Workflow

on:
    push:
        branches:
            - main
            - develop
    pull_request:
        branches:
            - main
            - develop

jobs:
    avoid-reduncy:
        name: Avoid Redundancy
        runs-on: ubuntu-latest
        steps:
            - name: Cancel previous redundant workflows
              uses: styfle/cancel-workflow-action@0.12.1

    build-test-lint:
        name: Build, Test and Lint
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go-version: ["1.23"]

        steps:
            - uses: actions/checkout@v4
            - name: Setup Go ${{ matrix.go-version }}
              uses: actions/setup-go@v5
              with:
                  go-version: ${{ matrix.go-version }}
            - name: Display Go version
              run: go version
            - name: Install dependencies
              run: |
                  make install
            - name: Run tests
              run: |
                  make test-json > TestResults-${{ matrix.go-version }}.json
            - name: Upload Go test results
              uses: actions/upload-artifact@v4
              with:
                  name: Go-results-${{ matrix.go-version }}
                  path: TestResults-${{ matrix.go-version }}.json
            - name: Run linters
              run: |
                  make lint
            - name: Build
              run: |
                  make build
